In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/Users/vijaypatidar/vijay/Anshul/deliver time prediction/data/Food_Delivery_1.csv")
df.sample(5)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
13433,0xbad7,INDORES08DEL01,36.0,4.2,22.725748,75.898497,22.795748,75.968497,04-04-2022,22:00:31,22:10:30,Sandstorms,Jam,0,Snack,motorcycle,2.0,Yes,Metropolitian,47
5325,0x76ee,HYDRES13DEL02,27.0,4.5,17.431477,78.400350,17.511477,78.480350,14-03-2022,20:32:48,20:47:02,Cloudy,Jam,0,Snack,motorcycle,2.0,No,Metropolitian,38
37831,0x6b25,PUNERES08DEL03,26.0,4.6,18.534080,73.898520,18.624080,73.988520,04-04-2022,22:13:09,22:28:13,Stormy,Low,1,Drinks,motorcycle,1.0,No,Metropolitian,18
10778,0xa3fb,VADRES13DEL02,31.0,5.0,22.310237,73.158921,22.440237,73.288921,04-04-2022,22:45:00,22:53:51,Sunny,Low,1,Buffet,scooter,0.0,No,Metropolitian,16
28835,0x6f30,RANCHIRES11DEL01,32.0,4.3,23.359194,85.325447,23.469194,85.435447,27-03-2022,20:00:29,20:06:42,Windy,Jam,1,Buffet,motorcycle,1.0,No,Metropolitian,42

In [ ]:
string_columns = [
    "Weatherconditions",
    "Road_traffic_density",
    "Type_of_order",
    "Type_of_vehicle",
    "Festival",
    "City"
]
for col in string_columns:
    df[col] = df[col].str.strip()

In [4]:
df["Road_traffic_density"].unique()

array(['High ', 'Jam ', 'Low ', 'Medium ', 'NaN '], dtype=object)

In [330]:
df["Road_traffic_density"].value_counts(dropna=False)

Low       14200
Jam       13043
Medium    10084
High       4071
NaN         555
Name: Road_traffic_density, dtype: int64

In [331]:
import numpy as np
for col in string_columns:
    df[col] = df[col].replace("NaN", np.nan)

In [332]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weatherconditions               569
Road_traffic_density            555
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                        215
City                           1114
Time_taken(min)                   0
dtype: int64

In [333]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41953 entries, 0 to 41952
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           41953 non-null  object
 1   Delivery_person_ID           41953 non-null  object
 2   Delivery_person_Age          41953 non-null  float64
 3   Delivery_person_Ratings      41953 non-null  float64
 4   Restaurant_latitude          41953 non-null  float64
 5   Restaurant_longitude         41953 non-null  float64
 6   Delivery_location_latitude   41953 non-null  float64
 7   Delivery_location_longitude  41953 non-null  float64
 8   Order_Date                   41953 non-null  object
 9   Time_Orderd                  40353 non-null  object
 10  Time_Order_picked            41953 non-null  object
 11  Weatherconditions            41384 non-null  object
 12  Road_traffic_density         41398 non-null  object
 13  Vehicle_condition            41953 non-null  int64
 14  Type_of_order                41953 non-null  object
 15  Type_of_vehicle              41953 non-null  object
 16  multiple_deliveries          41953 non-null  float64
 17  Festival                     41738 non-null  object
 18  City                         40839 non-null  object
 19  Time_taken(min)              41953 non-null  int64
dtypes: float64(7), int64(2), object(11)
memory usage: 6.4+ MB

In [334]:
df["Weatherconditions"] = df["Weatherconditions"].fillna(
    df["Weatherconditions"].mode()[0]
)

In [335]:
df["Road_traffic_density"] = df["Road_traffic_density"].fillna(
    df["Road_traffic_density"].mode()[0]
)

In [336]:
df["Festival"] = df["Festival"].fillna(
    df["Festival"].mode()[0]
)

In [337]:
df["City"] = df["City"].fillna(
    df["City"].mode()[0]
)

In [338]:
from math import radians, sin, cos, sqrt, atan2
def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in KM
    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = (
        sin(dlat / 2) ** 2
        + cos(lat1)
        * cos(lat2)
        * sin(dlon / 2) ** 2
    )
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

In [339]:
df["Delivery_Distance"] = df.apply(
    lambda row: haversine_distance(
        row["Restaurant_latitude"],
        row["Restaurant_longitude"],
        row["Delivery_location_latitude"],
        row["Delivery_location_longitude"]
    ),
    axis=1
)

In [340]:
df["Delivery_Distance"].head()

0     3.025149
1    20.183530
2     1.552758
3     7.790401
4     6.210138
Name: Delivery_Distance, dtype: float64

In [341]:
df["Delivery_Distance"].describe()

count    41953.000000
mean         9.720284
std          5.603083
min          1.465067
25%          4.657655
50%          9.193021
75%         13.680920
max         20.969489
Name: Delivery_Distance, dtype: float64

In [342]:
df[
    [
        "Time_Orderd",
        "Time_Order_picked"
    ]
].dtypes

Time_Orderd          object
Time_Order_picked    object
dtype: object

In [343]:
df["Time_Orderd"] = pd.to_datetime(
    df["Time_Orderd"],
    format="%H:%M:%S",
    errors="coerce"
)

df["Time_Order_picked"] = pd.to_datetime(
    df["Time_Order_picked"],
    format="%H:%M:%S",
    errors="coerce"
)

In [344]:
df["Preparation_Time"] = (
    df["Time_Order_picked"] -
    df["Time_Orderd"]
).dt.total_seconds() / 60

df.loc[
    df["Preparation_Time"] < 0,
    "Preparation_Time"
] += 24 * 60

In [345]:
df[
    [
        "Time_Orderd",
        "Time_Order_picked",
        "Preparation_Time"
    ]
].head()

          Time_Orderd   Time_Order_picked  Preparation_Time
0 1900-01-01 11:33:33 1900-01-01 11:45:29         11.933333
1 1900-01-01 19:45:37 1900-01-01 19:51:49          6.200000
2 1900-01-01 08:32:58 1900-01-01 08:48:47         15.816667
3 1900-01-01 18:03:58 1900-01-01 18:12:52          8.900000
4 1900-01-01 13:34:16 1900-01-01 13:45:36         11.333333

In [346]:
df["Order_Date"].dtype

dtype('O')

In [347]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)
df["Order_Date"].head()

0   2022-03-19
1   2022-03-25
2   2022-03-19
3   2022-04-05
4   2022-03-26
Name: Order_Date, dtype: datetime64[ns]

In [348]:
df["Order_Hour"] = df["Time_Orderd"].dt.hour
df["Order_Hour"].sample(4)

28074    23.0
25302    23.0
28467    23.0
9924     21.0
Name: Order_Hour, dtype: float64

In [349]:
df["Order_Minute"] = df["Time_Orderd"].dt.minute
df["Order_Minute"].head()

0    33.0
1    45.0
2    32.0
3     3.0
4    34.0
Name: Order_Minute, dtype: float64

In [350]:
df["Day_of_Week"] = df["Order_Date"].dt.day_name()
df['Day_of_Week'].head()

0    Saturday
1      Friday
2    Saturday
3     Tuesday
4    Saturday
Name: Day_of_Week, dtype: object

In [351]:
df["Month"] = df["Order_Date"].dt.month
df['Month'].head()

0    3
1    3
2    3
3    4
4    3
Name: Month, dtype: int64

In [352]:
df["Is_Weekend"] = (
    df["Order_Date"]
      .dt.dayofweek
      .isin([5, 6])
      .astype(int)
)
df["Is_Weekend"].head()

0    1
1    0
2    1
3    0
4    1
Name: Is_Weekend, dtype: int64

In [353]:
df[
    [
        "Order_Date",
        "Time_Orderd",
        "Order_Hour",
        "Order_Minute",
        "Day_of_Week",
        "Month",
        "Is_Weekend"
    ]
].head()

,Order_Date,Time_Orderd,Order_Hour,Order_Minute,Day_of_Week,Month,Is_Weekend
0,2022-03-19,1900-01-01 11:33:33,11.0,33.0,Saturday,3,1
1,2022-03-25,1900-01-01 19:45:37,19.0,45.0,Friday,3,0
2,2022-03-19,1900-01-01 08:32:58,8.0,32.0,Saturday,3,1
3,2022-04-05,1900-01-01 18:03:58,18.0,3.0,Tuesday,4,0
4,2022-03-26,1900-01-01 13:34:16,13.0,34.0,Saturday,3,1

In [354]:
df.sample(5)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Festival,City,Time_taken(min),Delivery_Distance,Preparation_Time,Order_Hour,Order_Minute,Day_of_Week,Month,Is_Weekend
11775,0xadb2,CHENRES07DEL02,36.0,4.5,13.081878,80.248519,13.101878,80.268519,2022-03-05,1900-01-01 08:38:42,...,No,Metropolitian,26,3.104463,13.566667,8.0,38.0,Saturday,3,1
19719,0xbc51,INDORES010DEL02,26.0,4.7,22.750040,75.902847,22.800040,75.952847,2022-04-03,1900-01-01 22:57:31,...,No,Metropolitian,19,7.562364,14.433333,22.0,57.0,Sunday,4,1
17559,0xa0c9,HYDRES15DEL01,30.0,4.4,17.459710,78.368855,17.469710,78.378855,2022-03-09,1900-01-01 08:57:23,...,No,Metropolitian,24,1.536716,15.133333,8.0,57.0,Wednesday,3,0
12292,0xa584,HYDRES20DEL03,33.0,4.3,17.483216,78.552111,17.573216,78.642111,2022-04-02,1900-01-01 20:53:07,...,No,Metropolitian,48,13.828141,16.733333,20.0,53.0,Saturday,4,1
14376,0x4a2f,HYDRES06DEL03,32.0,4.1,17.455894,78.375467,17.485894,78.405467,2022-03-19,1900-01-01 22:29:55,...,No,Metropolitian,30,4.610073,11.166667,22.0,29.0,Saturday,3,1

In [355]:
drop_columns = [
    "ID",
    "Delivery_person_ID",

    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude",

    "Order_Date",
    "Time_Orderd",
    "Time_Order_picked",

    "Preparation_Time"
]

In [356]:
df=df.drop(columns=drop_columns)

In [357]:
df.sample(5)

,Delivery_person_Age,Delivery_person_Ratings,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min),Delivery_Distance,Order_Hour,Order_Minute,Day_of_Week,Month,Is_Weekend
2294,24.0,4.8,Sandstorms,Medium,2,Drinks,motorcycle,1.0,No,Metropolitian,15,14.022322,18.0,42.0,Thursday,3,0
19643,37.0,4.4,Windy,Medium,1,Meal,scooter,0.0,No,Metropolitian,32,16.635315,18.0,18.0,Sunday,3,1
27717,34.0,4.3,Fog,Medium,2,Drinks,motorcycle,2.0,No,Urban,40,19.875681,17.0,14.0,Sunday,3,1
3121,26.0,4.8,Sandstorms,Jam,1,Snack,motorcycle,0.0,No,Metropolitian,25,8.929061,21.0,41.0,Tuesday,2,0
6038,23.0,4.9,Sandstorms,Medium,0,Buffet,motorcycle,0.0,No,Metropolitian,39,20.888261,17.0,55.0,Wednesday,2,0

In [358]:
df.shape

(41953, 17)

In [359]:
df.columns.tolist()

['Delivery_person_Age',
 'Delivery_person_Ratings',
 'Weatherconditions',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City',
 'Time_taken(min)',
 'Delivery_Distance',
 'Order_Hour',
 'Order_Minute',
 'Day_of_Week',
 'Month',
 'Is_Weekend']

In [360]:
df.shape

(41953, 17)

In [361]:
df = df.dropna(
    subset=["Order_Hour", "Order_Minute"]
)
df.shape

(40353, 17)

In [362]:
df.isnull().sum()

Delivery_person_Age        0
Delivery_person_Ratings    0
Weatherconditions          0
Road_traffic_density       0
Vehicle_condition          0
Type_of_order              0
Type_of_vehicle            0
multiple_deliveries        0
Festival                   0
City                       0
Time_taken(min)            0
Delivery_Distance          0
Order_Hour                 0
Order_Minute               0
Day_of_Week                0
Month                      0
Is_Weekend                 0
dtype: int64

In [363]:
df.to_csv(
    "../data/food_delivery_processed.csv",
    index=False
)