In [58]:
import pandas as pd
df_model = pd.read_csv("/Users/vijaypatidar/vijay/Anshul/deliver time prediction/data/food_delivery_processed.csv")

In [59]:
X = df_model.drop(columns="Time_taken(min)")
y = df_model["Time_taken(min)"]

In [60]:
print(X.shape)
print(y.shape)

(41953, 16)
(41953,)

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
    y,
    test_size=0.20,random_state=42
)

In [62]:
print("X Train :", X_train.shape)
print("X Test :", X_test.shape)
print("Y Train :", y_train.shape)
print("Y Test :", y_test.shape)

X Train : (33562, 16)
X Test : (8391, 16)
Y Train : (33562,)
Y Test : (8391,)

In [63]:
df_model.sample(5)

,Delivery_person_Age,Delivery_person_Ratings,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min),Delivery_Distance,Order_Hour,Order_Minute,Day_of_Week,Month,Is_Weekend
23721,38.0,4.7,Stormy,Low,2,Drinks,electric_scooter,1.0,No,Metropolitian,26,1.558115,10.0,39.0,Friday,3,0
41758,30.0,4.7,Sandstorms,Jam,2,Drinks,scooter,1.0,No,Metropolitian,22,10.881078,21.0,43.0,Tuesday,3,0
25480,26.0,4.7,Sandstorms,High,0,Snack,motorcycle,1.0,No,Urban,28,3.104572,11.0,28.0,Tuesday,4,0
39070,34.0,4.8,Cloudy,Jam,1,Meal,motorcycle,0.0,No,Metropolitian,26,7.660206,21.0,16.0,Sunday,3,1
3767,24.0,4.9,Cloudy,Low,2,Snack,motorcycle,0.0,No,Metropolitian,21,10.428149,22.0,33.0,Saturday,3,1

In [64]:
numerical_features = [
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Vehicle_condition",
    "multiple_deliveries",
    "Delivery_Distance",
    "Order_Hour",
    "Order_Minute",
    "Month",
    "Is_Weekend"
]

categorical_features = [
    "Weatherconditions",
    "Road_traffic_density",
    "Type_of_order",
    "Type_of_vehicle",
    "Festival",
    "City",
    "Day_of_Week"
]

In [65]:
print("Numerical Features")
print(numerical_features)
print("\nCategorical Features")
print(categorical_features)

Numerical Features
['Delivery_person_Age', 'Delivery_person_Ratings', 'Vehicle_condition', 'multiple_deliveries', 'Delivery_Distance', 'Order_Hour', 'Order_Minute', 'Month', 'Is_Weekend']

Categorical Features
['Weatherconditions', 'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle', 'Festival', 'City', 'Day_of_Week']

In [66]:
df_model[categorical_features].sample(5)

,Weatherconditions,Road_traffic_density,Type_of_order,Type_of_vehicle,Festival,City,Day_of_Week
40221,Sandstorms,High,Buffet,motorcycle,No,Metropolitian,Sunday
6613,Fog,Low,Snack,motorcycle,No,Metropolitian,Sunday
11729,Sandstorms,Medium,Snack,scooter,No,Metropolitian,Wednesday
15673,Cloudy,Medium,Buffet,motorcycle,No,Metropolitian,Thursday
11203,Cloudy,Medium,Snack,motorcycle,No,Urban,Saturday

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder,
    OrdinalEncoder
)

In [74]:
numerical_features = [
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Vehicle_condition",
    "multiple_deliveries",
    "Delivery_Distance",
    "Order_Hour",
    "Order_Minute",
    "Month",
    "Is_Weekend"
]

In [69]:
ordinal_feature = [
    "Road_traffic_density"
]

In [75]:
onehot_features = [
    "Weatherconditions",
    "Type_of_order",
    "Type_of_vehicle",
    "Festival",
    "City",
    "Day_of_Week"
]

In [76]:
num_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

In [77]:
num_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

NameError: name 'SimpleImputer' is not defined